services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt
      - npm-logs:/data/logs
  goaccess:
    image: justsky/goaccess-for-nginxproxymanager:latest
    container_name: goaccess
    restart: unless-stopped
    environment:
      - TZ=Australia/Melbourne
    ports:
      - 7880:7880
    volumes:
      - npm-logs:/opt/log
volumes:
  npm-data:
    driver: local
  npm-letsencrypt:
    driver: local
  npm-logs:
    driver: local
